extern int file_exists(const char *filename);
extern int mod_readbm(char *bmfile);
extern int mod_writebm(int mode);
extern int mod_colidx(char* rstr, char *ostr, int idx, char del);
extern int zip_bintype(char *btype, const char *cext);
extern int zip_isbin(char *cext);
extern int cplocaldisk();
extern int customcfg();
extern int p_customcfg();
extern int dealwithzip(int keep);
extern int mod_optype(const char *stmt);
extern int env_get(char *val, const char *var);
extern int env_cmp(char *senv);
extern int cmd_gethdx(char *myhd, char *type, char *loc);
extern int cmd_insthdi();
extern int cmd_insthdd();
extern int cmd_gethdi(char *myhd);
extern int cmd_gethdd(char *myhd);
extern int cmd_getwd(char *wd);
extern int cmd_getcmdline(char *bintype);
extern int cmd_getvar(char *currl, char *currvar);
extern int cmd_scanvar(char *strout, const char *strin);
extern int build_cmd();
extern int cmdtbl_clear();
extern int cmdtbl_new(char *sopt,char *senv, char *scmd);
extern int cmdtbl_replace(char *sopt,char *senv, char *scmd);
extern int cmdtbl_alter(char *sopt,char *senv, char *scmd);
extern int cmdtbl_print();
extern int env_clear();
extern int env_print();
extern int env_isset(const char *svar);
extern int env_set(char *senv);
extern int env_load(const char *emuenv);
extern int mod_cleantmp();
extern int setbootdisk();
extern int load_settings();
extern int mod_loadcfg(const char *emucfg);
extern int mod_loademucfg();
extern int mod_loadsyscfg();
extern int mod_loadpergame();
extern int mod_getsystem(char *msys, char *msysbase);
extern int mod_searchbin(char *btype,char *fqfile, const char *filen);	
extern int mod_exportvars();
extern int mod_getbintype(char *btype);   
extern int bin2disk();
extern int process_cmd(char *cmd);   
extern int emumodule_generic();
extern int emumodule_computer();
extern int sysmodule_arcade();
extern int sysmodule_generic();
extern int sysmodule_computer();
extern int module_exec();
